[package]
name = "raytracer"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.20.2"
rand_distr = { version = "0.4.3", default-features = false }
rand_pcg = "0.3.1"

[features]
std = ["rand_distr/std"]
