[package]
name = "native-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
raytracer = { path = "../raytracer" }
log = "0.4.16"
env_logger = "0.9.0"
pollster = "0.2.5"
clap = { version = "3.1.6", features = ["derive"] }
