[package]
name = "native-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
raytracer = { path = "../raytracer" }
log = "0.4.16"
env_logger = "0.11.3"
pollster = "0.3.0"
clap = { version = "4.5.4", features = ["derive"] }
