[package]
name = "raytracer-driver"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.9.0"
libloading = "0.7.3"
log = "0.4.14"
notify = "4.0.17"
pixels = "0.9.0"
raytracer-common = { path = "../common" }
winit = "0.26.1"

[features]
